### ISSUE TITLE
Validation/Testing split

### ISSUE THREAD

**Issue by tsun** [lisadunlap/LADS#16]
Thanks for the nice work! I am trying to reproduce the results and have a few questions on the details. Appreciate any help :)

I see in Supp.B, the Validation/Testing data of CUB-Paintings and DomainNet are equally divided from the ID data, e.g., 2897 for validation and 2897 for testing. But when I run your code, the val_loader includes all 5794/2399 ID data, and test_loader only includes OOD data. I wonder whether the Validataion/Testing are randomly split? Do I need to modify the code of get_dataset to implement this splitting?

For Waterbirds, after getting the test group acc={0:99.65，1:71.18， 2:69.47，3:95.64}, I use the following formula to calculate ID/OOD test acc of LADS (as reported in Fig.3(b)):
ID = (99.65*2255+95.64*642)/(2255+642)=98.76
ODD = (71.18*2255+69.47*642)/(2255+642)=70.80
Am I doing it in the correct way?

I would also like to try Colored MNIST, but I did not find the the right place to download this dataset used in the paper.

**Comment by lisadunlap** [comment]
Ah yes, thank you for pointing that out. It's a result of some legacy code, I believe the current dataset loads validation data has ID data and test loader has OOD data, then when we [load the embeddings](https://github.com/lisadunlap/LADS/blob/114e025c5ccf4595f67983dc2ccc0dc7252ef1cd/main.py#L82) we put half the val set into the test set. I have a much cleaner version of the code that solves this problem that is likely to come out in the next week or so. But for now you shouldn't need to modify anything in the code :)

The way we calculate ID and OOD data is by averaging the groups together. So 
ID = (99.652255+95.64642)/2=97.55
ODD = (71.182255+69.47642)/2=70.392

Sorry for not including ColoredMNIST! I actually just manually changed the color the MNIST digits :p 
Later today I can add the notebook to produce the dataset as well as the embeddings and configs (if they arent already there)

**Comment by tsun** [comment]
Thanks for your quick response! It solves my issues.

I did not use DATA.LOAD_CACHED. That's why I missed this Line 82. 

For a clarification, my original formula is weighted average (\* not rendered properly). But unweighted average makes sense to me.
ID = (99.65\*2255+95.64\*642)/(2255+642)=98.76
ODD = (71.18\*2255+69.47\*642)/(2255+642)=70.80

A minor issue is that wandb Checkpoints for Waterbirds/ColoredMNIST are inaccessible. The other two work perfectly.

**Comment by daiqing-qi** [comment]
> load the embeddings

@tsun Hi, may I ask if you successfully reproduced the results on CUB dataset? My reproduced results are: 
64.75 (OOD)
86.02 (ID)
75.118 (Extended)
The OOD result is obviously lower than reported  66.18± 0.25%.
