### ISSUE TITLE
Encoder Type of WaterBirds

### ISSUE THREAD

**Issue by Phoenix-V** [lisadunlap/LADS#22]
May I know what the encoder used to extract features on WaterBirds is? I have used the ViT-L/14 embedding in the repo for linear probing. However, the performance is much higher (>80) than the number reported in paper Figure 3b (62.12)

**Comment by lisadunlap** [comment]
Apologies for the late reply! We do use the ViT-L/14 embedding. I updated the arxiv paper with some updated numbers so please let me know if you are running into the same issue.
