### ISSUE TITLE
load_embeddings 

### ISSUE THREAD

**Issue by HHTseng** [lisadunlap/LADS#23]
Hi,
when running `python main.py --config configs/Waterbirds/mlp.yaml`, I encountered: `NameError: name 'load_embeddings' is not defined` in main.py [line 91](https://github.com/lisadunlap/LADS/blob/5dc41d68c16ccbf8eff74465eff11722717b59f0/main.py#L91):, i.e.,
```
train_features, train_labels, train_groups, train_domains, train_filenames, val_features, val_labels, val_groups, val_domains, val_filenames, test_features, test_labels, test_groups, test_domains, test_filenames = load_embeddings(cache_file, args.DATA.DATASET)
```
It seems that one should include `load_embeddings` from `clip_utils` to make it work properly, using
```
from clip_utils import load_embeddings
``` 
Could you confirm this is a legitimate way to fix the error? Thank you.

**Comment by lisadunlap** [comment]
yup that should work! Thanks for pointing that out, I will update with the fix
